# Streamlit Secrets

GEMINI_API_KEY = "AIzaSyCphQ0JUb6g9vbStxedg9uMZht0e_9BI8I"

[firebase_credentials]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"

private_key = """-----BEGIN PRIVATE KEY-----
YOUR_MULTI_LINE_PRIVATE_KEY_HERE
-----END PRIVATE KEY-----"""

client_email = "your-client-email@.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your-client-x509-cert-url"
